language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_install:
    - composer self-update --no-interaction

install:
    - composer install --no-interaction --prefer-source
    - gem install mailcatcher

before_script:
    - mailcatcher --smtp-port 4456

script:
    - phpunit --verbose
